# Generated by Django 3.2.7 on 2022-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=b'I01\n', upload_to='posts'),
            preserve_default=b'I01\n',
        ),
    ]
